MVC5UI/Controllers/datetimepickerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5UI.Controllers
{
    public class datetimepickerController : Controller
    {
        // GET: datetimepicker
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC5UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC5UI</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC5UI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#menu-toggle" id="menu-toggle2">Sidebar &raquo;</a></li>
                    <li>@Html.ActionLink("HomePage", "Index", "Home")</li>
                    <li>@Html.ActionLink("Account", "Index", "Account")</li>
                    <li>@Html.ActionLink("Datetimepicker", "Index", "datetimepicker")</li>
                    <li>@Html.ActionLink("DataAnnotations", "Index", "DataAnnotations")</li>
                    <li>
                        <a data-toggle="dropdown" href="#">
                            Encryption
                            <span class="fa fa-caret-down" title="Toggle dropdown menu"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/Encryption/HashMD5">HashMD5</a></li>
                            <li class="divider"></li>
                            <li><a href="/Encryption/HashSHA1">HashSHA1</a></li>
                            <li><a href="/Encryption/HashSHA256">HashSHA256</a></li>                           
                            <li><a href="/Encryption/HashSHA384">HashSHA384</a></li>
                            <li><a href="/Encryption/HashSHA512">HashSHA512</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MVC5UI</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>